title: Lisa (Taylor) Ferguson
description: Software Developer | Educator | Writer
theme: minima
header_pages:
  - index.md
  - resume.md
  - software-developer.md
  - educator.md
  - writing.md
  - contact.md
